/**
MIT License

Copyright (c) 2023 Yunex Limited

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

package main

import (
	"encoding/hex"
	"flag"
	"fmt"
	"io/ioutil"
	"os"
	"testapp/ipmtscd"

	"github.com/TOPAS-2545/ber"
)

func check(e error) {
	if e != nil {
		panic(e)
	}
}

func create_message() {

	fmt.Println("Performing encode")

	occData := IPMTSCD.OccupancyBasedDetectionData{
		OccupancyState:                 true,
		OccupancyStateDuration:         33,
		OccupancyPreviousStateDuration: 33,
		OccupancyRate:                  55.8,
		Volume:                         77,
	}

	// Marshal the occupancy data with tag:1 for the CHOICE encoding
	// CHOICE tags: [1]=occupancy, [2]=image, [3]=identification,
	// [4]=occupancyType2, [5]=imageType2, [6]=identificationType2
	generatedInnerBytes, err := ber.MarshalWithParams(occData, "tag:1")

	fmt.Printf("generatedInnerBytes: %+v \n", generatedInnerBytes)

	if err != nil {
		fmt.Println("Failed to marshall message: ", err.Error())
	}

	detectorInfo := []IPMTSCD.DetectorInfoSeq{
		{
			PhysicalDetectorIndex: 0,
			InfoType:              0,
			// Wrap the detection data into DetectionInfo with context-specific constructed tag
			DetectionInfo: ber.RawValue{Class: ber.ClassContextSpecific, Tag: 2, IsCompound: true, Bytes: generatedInnerBytes},
		},
	}

	fmt.Printf("detectorInfo: %+v \n", detectorInfo)

	expected := IPMTSCD.IpmstscdData{
		// Add the detector controller information
		DetectorControllerInfo: &IPMTSCD.DetectorControllerInfo{
			DetectorControllerIndex: 5,
		},

		// Add the detector data
		DetectorInfo: detectorInfo,
	}

	generatedBytes, err := ber.Marshal(expected)

	err = os.WriteFile("../golang-detector.ber", generatedBytes, 0644)
	check(err)

	fmt.Println("generation complete")

}

func main() {

	var mode string

	mySet := flag.NewFlagSet("", flag.ExitOnError)
	mySet.StringVar(&mode, "m", "mode", "the operation to perform")
	mySet.Parse(os.Args[1:])

	if mode == "create" {
		create_message()
	}

	if mode == "recode" {

		// load in the file
		fmt.Println("Performing recode")

		// load in the BER generated by the python system
		contents, _ := ioutil.ReadFile("../python-detector.ber")

		var t IPMTSCD.IpmstscdData

		_, err1 := ber.Unmarshal(contents, &t)

		check(err1)

		fmt.Printf("IpmstscdData: %+v \n", t)

		if len(t.DetectorInfo) > 0 {

			for i := range t.DetectorInfo {
				detInfo := &t.DetectorInfo[i]

				// The DetectionInfo is wrapped in an explicit tag [2].
				// The actual CHOICE tag is the first tag inside the Bytes.
				// Parse the inner tag to determine the CHOICE variant.
				innerBytes := detInfo.DetectionInfo.Bytes
				if len(innerBytes) < 2 {
					fmt.Fprintf(os.Stderr, "Error: DetectionInfo bytes too short for detector %d\n", i)
					os.Exit(1)
				}
				// The first byte of innerBytes contains the CHOICE tag
				// Context-specific constructed: 0xa0 | tag_number
				choiceTag := int(innerBytes[0] & 0x1f)

				fmt.Printf("Detector %d: InfoType=%d, CHOICE tag=%d\n", i, detInfo.InfoType, choiceTag)
				fmt.Printf(hex.Dump(innerBytes))

				var generatedInnerBytes []byte
				var marshalErr error

				switch choiceTag {
				case 1:
					// OccupancyBasedDetectionData
					var occData IPMTSCD.OccupancyBasedDetectionData
					_, err2 := ber.UnmarshalWithParams(detInfo.DetectionInfo.Bytes, &occData, "tag:1")
					check(err2)
					fmt.Printf("OccupancyBasedDetectionData: %+v\n", occData)
					generatedInnerBytes, marshalErr = ber.MarshalWithParams(occData, "tag:1")
					check(marshalErr)

				case 2:
					// ImageProcessingBasedDetectionData
					var imgData IPMTSCD.ImageProcessingBasedDetectionData
					_, err2 := ber.UnmarshalWithParams(detInfo.DetectionInfo.Bytes, &imgData, "tag:2")
					check(err2)
					fmt.Printf("ImageProcessingBasedDetectionData: %+v\n", imgData)
					generatedInnerBytes, marshalErr = ber.MarshalWithParams(imgData, "tag:2")
					check(marshalErr)

				case 3:
					// IdentificationBasedDetectionData
					var idData IPMTSCD.IdentificationBasedDetectionData
					_, err2 := ber.UnmarshalWithParams(detInfo.DetectionInfo.Bytes, &idData, "tag:3")
					check(err2)
					fmt.Printf("IdentificationBasedDetectionData: %+v\n", idData)
					generatedInnerBytes, marshalErr = ber.MarshalWithParams(idData, "tag:3")
					check(marshalErr)

				case 4:
					// OccupancyBasedDetectionDataType2
					var occType2 IPMTSCD.OccupancyBasedDetectionDataType2
					_, err2 := ber.UnmarshalWithParams(detInfo.DetectionInfo.Bytes, &occType2, "tag:4")
					check(err2)
					fmt.Printf("OccupancyBasedDetectionDataType2: %+v\n", occType2)
					generatedInnerBytes, marshalErr = ber.MarshalWithParams(occType2, "tag:4")
					check(marshalErr)

				case 5:
					// ImageProcessingBasedDetectionDataType2
					var imgType2 IPMTSCD.ImageProcessingBasedDetectionDataType2
					_, err2 := ber.UnmarshalWithParams(detInfo.DetectionInfo.Bytes, &imgType2, "tag:5")
					check(err2)
					fmt.Printf("ImageProcessingBasedDetectionDataType2: %+v\n", imgType2)
					generatedInnerBytes, marshalErr = ber.MarshalWithParams(imgType2, "tag:5")
					check(marshalErr)

				case 6:
					// IdentificationBasedDetectionDataType2
					var idType2 IPMTSCD.IdentificationBasedDetectionDataType2
					_, err2 := ber.UnmarshalWithParams(detInfo.DetectionInfo.Bytes, &idType2, "tag:6")
					check(err2)
					fmt.Printf("IdentificationBasedDetectionDataType2: %+v\n", idType2)
					generatedInnerBytes, marshalErr = ber.MarshalWithParams(idType2, "tag:6")
					check(marshalErr)

				default:
					fmt.Fprintf(os.Stderr, "Error: unrecognised detection info type: tag %d\n", choiceTag)
					os.Exit(1)
				}

				// Re-wrap the marshalled inner bytes into the DetectionInfo RawValue
				// The RawValue stores the explicit tag [2] and the inner CHOICE-tagged content as Bytes
				detInfo.DetectionInfo = ber.RawValue{Class: ber.ClassContextSpecific, Tag: 2, IsCompound: true, Bytes: generatedInnerBytes}
			}
		}

		fmt.Printf("t: %+v \n", t)

		// Re-encode the whole message
		generatedBytes, err := ber.Marshal(t)

		err = os.WriteFile("../golang-detector.ber", generatedBytes, 0644)
		check(err)
	}
}
