/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AccumulativeDetectionSeq_H_
#define	_AccumulativeDetectionSeq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AccumulativeDetectionSeq__detectionStatus {
	AccumulativeDetectionSeq__detectionStatus_normal	= 0,
	AccumulativeDetectionSeq__detectionStatus_failure	= 1,
	AccumulativeDetectionSeq__detectionStatus_dataInvalid	= 2
} e_AccumulativeDetectionSeq__detectionStatus;

/* AccumulativeDetectionSeq */
typedef struct AccumulativeDetectionSeq {
	long	 detectorNumber;
	long	*detectionStatus	/* OPTIONAL */;
	long	 density;
	long	 occupancy;
	long	 detectorPulseError;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccumulativeDetectionSeq_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_detectionStatus_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_AccumulativeDetectionSeq;

#ifdef __cplusplus
}
#endif

#endif	/* _AccumulativeDetectionSeq_H_ */
#include <asn_internal.h>
