/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#include "DetectorInfoSeq.h"

static int
infoType_3_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
infoType_3_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
infoType_3_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	infoType_3_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
infoType_3_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	infoType_3_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
infoType_3_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	infoType_3_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
infoType_3_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	infoType_3_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
infoType_3_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	infoType_3_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
infoType_3_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	infoType_3_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
memb_physicalDetectorIndex_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static const asn_INTEGER_enum_map_t asn_MAP_infoType_value2enum_3[] = {
	{ 1,	21,	"occupancyTypeDetector" },
	{ 2,	17,	"imageTypeDetector" },
	{ 3,	18,	"idBaseTypeDetector" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_infoType_enum2value_3[] = {
	2,	/* idBaseTypeDetector(3) */
	1,	/* imageTypeDetector(2) */
	0	/* occupancyTypeDetector(1) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_infoType_specs_3 = {
	asn_MAP_infoType_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_infoType_enum2value_3,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	4,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_infoType_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_infoType_3 = {
	"infoType",
	"infoType",
	infoType_3_free,
	infoType_3_print,
	infoType_3_constraint,
	infoType_3_decode_ber,
	infoType_3_encode_der,
	infoType_3_decode_xer,
	infoType_3_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_infoType_tags_3,
	sizeof(asn_DEF_infoType_tags_3)
		/sizeof(asn_DEF_infoType_tags_3[0]) - 1, /* 1 */
	asn_DEF_infoType_tags_3,	/* Same as above */
	sizeof(asn_DEF_infoType_tags_3)
		/sizeof(asn_DEF_infoType_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_infoType_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_detectionInfo_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DetectorInfoSeq__detectionInfo, choice.occupancyBasedDetectionData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OccupancyBasedDetectionData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancyBasedDetectionData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectorInfoSeq__detectionInfo, choice.imageProcessingBasedDetectionData),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ImageProcessingBasedDetectionData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imageProcessingBasedDetectionData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectorInfoSeq__detectionInfo, choice.identificationBasedDetectionData),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IdentificationBasedDetectionData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"identificationBasedDetectionData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectorInfoSeq__detectionInfo, choice.occupancyTypeDetectionInfoType2),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OccupancyBasedDetectionDataType2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancyTypeDetectionInfoType2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectorInfoSeq__detectionInfo, choice.imageProcessingBasedDetectionDataType2),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ImageProcessingBasedDetectionDataType2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imageProcessingBasedDetectionDataType2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectorInfoSeq__detectionInfo, choice.identificationBasedDetectionDataType2),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IdentificationBasedDetectionDataType2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"identificationBasedDetectionDataType2"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_detectionInfo_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* occupancyBasedDetectionData */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* imageProcessingBasedDetectionData */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* identificationBasedDetectionData */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* occupancyTypeDetectionInfoType2 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* imageProcessingBasedDetectionDataType2 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 } /* identificationBasedDetectionDataType2 */
};
static asn_CHOICE_specifics_t asn_SPC_detectionInfo_specs_8 = {
	sizeof(struct DetectorInfoSeq__detectionInfo),
	offsetof(struct DetectorInfoSeq__detectionInfo, _asn_ctx),
	offsetof(struct DetectorInfoSeq__detectionInfo, present),
	sizeof(((struct DetectorInfoSeq__detectionInfo *)0)->present),
	asn_MAP_detectionInfo_tag2el_8,
	6,	/* Count of tags in the map */
	0,
	6	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_detectionInfo_8 = {
	"detectionInfo",
	"detectionInfo",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_detectionInfo_8,
	6,	/* Elements count */
	&asn_SPC_detectionInfo_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DetectorInfoSeq_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DetectorInfoSeq, physicalDetectorIndex),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_physicalDetectorIndex_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"physicalDetectorIndex"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectorInfoSeq, infoType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_infoType_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"infoType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DetectorInfoSeq, detectionInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_detectionInfo_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"detectionInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct DetectorInfoSeq, detectorTimeLocation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralTimeLocationCore,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"detectorTimeLocation"
		},
};
static const ber_tlv_tag_t asn_DEF_DetectorInfoSeq_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DetectorInfoSeq_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* physicalDetectorIndex */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* infoType */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* detectionInfo */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* detectorTimeLocation */
};
static asn_SEQUENCE_specifics_t asn_SPC_DetectorInfoSeq_specs_1 = {
	sizeof(struct DetectorInfoSeq),
	offsetof(struct DetectorInfoSeq, _asn_ctx),
	asn_MAP_DetectorInfoSeq_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DetectorInfoSeq = {
	"DetectorInfoSeq",
	"DetectorInfoSeq",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DetectorInfoSeq_tags_1,
	sizeof(asn_DEF_DetectorInfoSeq_tags_1)
		/sizeof(asn_DEF_DetectorInfoSeq_tags_1[0]), /* 1 */
	asn_DEF_DetectorInfoSeq_tags_1,	/* Same as above */
	sizeof(asn_DEF_DetectorInfoSeq_tags_1)
		/sizeof(asn_DEF_DetectorInfoSeq_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DetectorInfoSeq_1,
	4,	/* Elements count */
	&asn_SPC_DetectorInfoSeq_specs_1	/* Additional specs */
};

