/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DetectorInfoSeq_H_
#define	_DetectorInfoSeq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "OccupancyBasedDetectionData.h"
#include "ImageProcessingBasedDetectionData.h"
#include "IdentificationBasedDetectionData.h"
#include "OccupancyBasedDetectionDataType2.h"
#include "ImageProcessingBasedDetectionDataType2.h"
#include "IdentificationBasedDetectionDataType2.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DetectorInfoSeq__infoType {
	DetectorInfoSeq__infoType_occupancyTypeDetector	= 1,
	DetectorInfoSeq__infoType_imageTypeDetector	= 2,
	DetectorInfoSeq__infoType_idBaseTypeDetector	= 3
	/*
	 * Enumeration is extensible
	 */
} e_DetectorInfoSeq__infoType;
typedef enum DetectorInfoSeq__detectionInfo_PR {
	DetectorInfoSeq__detectionInfo_PR_NOTHING,	/* No components present */
	DetectorInfoSeq__detectionInfo_PR_occupancyBasedDetectionData,
	DetectorInfoSeq__detectionInfo_PR_imageProcessingBasedDetectionData,
	DetectorInfoSeq__detectionInfo_PR_identificationBasedDetectionData,
	DetectorInfoSeq__detectionInfo_PR_occupancyTypeDetectionInfoType2,
	DetectorInfoSeq__detectionInfo_PR_imageProcessingBasedDetectionDataType2,
	DetectorInfoSeq__detectionInfo_PR_identificationBasedDetectionDataType2,
	/* Extensions may appear below */
	
} DetectorInfoSeq__detectionInfo_PR;

/* Forward declarations */
struct GeneralTimeLocationCore;

/* DetectorInfoSeq */
typedef struct DetectorInfoSeq {
	long	 physicalDetectorIndex;
	long	 infoType;
	struct DetectorInfoSeq__detectionInfo {
		DetectorInfoSeq__detectionInfo_PR present;
		union DetectorInfoSeq__detectionInfo_u {
			OccupancyBasedDetectionData_t	 occupancyBasedDetectionData;
			ImageProcessingBasedDetectionData_t	 imageProcessingBasedDetectionData;
			IdentificationBasedDetectionData_t	 identificationBasedDetectionData;
			OccupancyBasedDetectionDataType2_t	 occupancyTypeDetectionInfoType2;
			ImageProcessingBasedDetectionDataType2_t	 imageProcessingBasedDetectionDataType2;
			IdentificationBasedDetectionDataType2_t	 identificationBasedDetectionDataType2;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} detectionInfo;
	struct GeneralTimeLocationCore	*detectorTimeLocation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DetectorInfoSeq_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_infoType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DetectorInfoSeq;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralTimeLocationCore.h"

#endif	/* _DetectorInfoSeq_H_ */
#include <asn_internal.h>
