/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DetectorControllerInfo_H_
#define	_DetectorControllerInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GeneralTimeLocationCore;

/* DetectorControllerInfo */
typedef struct DetectorControllerInfo {
	long	 detectorControllerIndex;
	struct GeneralTimeLocationCore	*detectorControllerTimeLocation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DetectorControllerInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DetectorControllerInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralTimeLocationCore.h"

#endif	/* _DetectorControllerInfo_H_ */
#include <asn_internal.h>
