/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DirectionalTrafficVolumeSeq_H_
#define	_DirectionalTrafficVolumeSeq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DirectionalTrafficVolumeSeq__detectionStatus {
	DirectionalTrafficVolumeSeq__detectionStatus_normal	= 0,
	DirectionalTrafficVolumeSeq__detectionStatus_failure	= 1,
	DirectionalTrafficVolumeSeq__detectionStatus_dataInvalid	= 2
} e_DirectionalTrafficVolumeSeq__detectionStatus;

/* DirectionalTrafficVolumeSeq */
typedef struct DirectionalTrafficVolumeSeq {
	long	 directionNumber;
	long	*detectionStatus	/* OPTIONAL */;
	long	 directionDensity;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DirectionalTrafficVolumeSeq_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_detectionStatus_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DirectionalTrafficVolumeSeq;

#ifdef __cplusplus
}
#endif

#endif	/* _DirectionalTrafficVolumeSeq_H_ */
#include <asn_internal.h>
