/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IdentificationBasedDetectionDataType2_H_
#define	_IdentificationBasedDetectionDataType2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <BIT_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IdentificationBasedDetectionDataType2__detectorStatus {
	IdentificationBasedDetectionDataType2__detectorStatus_processingFailure	= 0,
	IdentificationBasedDetectionDataType2__detectorStatus_operatingFailure	= 1
} e_IdentificationBasedDetectionDataType2__detectorStatus;

/* Forward declarations */
struct AccumulativeDetectionSeq;
struct PassingVehicleTimeSeriesSeq;
struct VehicleSpeedSeq;
struct VehicleIdentificationSeq;

/* IdentificationBasedDetectionDataType2 */
typedef struct IdentificationBasedDetectionDataType2 {
	struct IdentificationBasedDetectionDataType2__accumulativeDetection {
		A_SEQUENCE_OF(struct AccumulativeDetectionSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} accumulativeDetection;
	struct IdentificationBasedDetectionDataType2__passingVehicleTimeSeries {
		A_SEQUENCE_OF(struct PassingVehicleTimeSeriesSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} passingVehicleTimeSeries;
	struct IdentificationBasedDetectionDataType2__vehicleSpeed {
		A_SEQUENCE_OF(struct VehicleSpeedSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} vehicleSpeed;
	OCTET_STRING_t	 specificVehicleDetection;
	struct IdentificationBasedDetectionDataType2__vehicleIdentification {
		A_SEQUENCE_OF(struct VehicleIdentificationSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} vehicleIdentification;
	BIT_STRING_t	*detectorStatus	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IdentificationBasedDetectionDataType2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IdentificationBasedDetectionDataType2;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AccumulativeDetectionSeq.h"
#include "PassingVehicleTimeSeriesSeq.h"
#include "VehicleSpeedSeq.h"
#include "VehicleIdentificationSeq.h"

#endif	/* _IdentificationBasedDetectionDataType2_H_ */
#include <asn_internal.h>
