/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#include "IdentificationBasedDetectionDataType2.h"

static int
memb_accumulativeDetection_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 48)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_passingVehicleTimeSeries_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 48)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_vehicleSpeed_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size <= 160)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_specificVehicleDetection_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 6)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_detectorStatus_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size >= 1 && size <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_accumulativeDetection_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AccumulativeDetectionSeq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_accumulativeDetection_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_accumulativeDetection_specs_2 = {
	sizeof(struct IdentificationBasedDetectionDataType2__accumulativeDetection),
	offsetof(struct IdentificationBasedDetectionDataType2__accumulativeDetection, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_accumulativeDetection_2 = {
	"accumulativeDetection",
	"accumulativeDetection",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_accumulativeDetection_tags_2,
	sizeof(asn_DEF_accumulativeDetection_tags_2)
		/sizeof(asn_DEF_accumulativeDetection_tags_2[0]) - 1, /* 1 */
	asn_DEF_accumulativeDetection_tags_2,	/* Same as above */
	sizeof(asn_DEF_accumulativeDetection_tags_2)
		/sizeof(asn_DEF_accumulativeDetection_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_accumulativeDetection_2,
	1,	/* Single element */
	&asn_SPC_accumulativeDetection_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_passingVehicleTimeSeries_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PassingVehicleTimeSeriesSeq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_passingVehicleTimeSeries_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_passingVehicleTimeSeries_specs_4 = {
	sizeof(struct IdentificationBasedDetectionDataType2__passingVehicleTimeSeries),
	offsetof(struct IdentificationBasedDetectionDataType2__passingVehicleTimeSeries, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_passingVehicleTimeSeries_4 = {
	"passingVehicleTimeSeries",
	"passingVehicleTimeSeries",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_passingVehicleTimeSeries_tags_4,
	sizeof(asn_DEF_passingVehicleTimeSeries_tags_4)
		/sizeof(asn_DEF_passingVehicleTimeSeries_tags_4[0]) - 1, /* 1 */
	asn_DEF_passingVehicleTimeSeries_tags_4,	/* Same as above */
	sizeof(asn_DEF_passingVehicleTimeSeries_tags_4)
		/sizeof(asn_DEF_passingVehicleTimeSeries_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_passingVehicleTimeSeries_4,
	1,	/* Single element */
	&asn_SPC_passingVehicleTimeSeries_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_vehicleSpeed_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_VehicleSpeedSeq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_vehicleSpeed_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_vehicleSpeed_specs_6 = {
	sizeof(struct IdentificationBasedDetectionDataType2__vehicleSpeed),
	offsetof(struct IdentificationBasedDetectionDataType2__vehicleSpeed, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_vehicleSpeed_6 = {
	"vehicleSpeed",
	"vehicleSpeed",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_vehicleSpeed_tags_6,
	sizeof(asn_DEF_vehicleSpeed_tags_6)
		/sizeof(asn_DEF_vehicleSpeed_tags_6[0]) - 1, /* 1 */
	asn_DEF_vehicleSpeed_tags_6,	/* Same as above */
	sizeof(asn_DEF_vehicleSpeed_tags_6)
		/sizeof(asn_DEF_vehicleSpeed_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_vehicleSpeed_6,
	1,	/* Single element */
	&asn_SPC_vehicleSpeed_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_vehicleIdentification_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_VehicleIdentificationSeq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_vehicleIdentification_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_vehicleIdentification_specs_9 = {
	sizeof(struct IdentificationBasedDetectionDataType2__vehicleIdentification),
	offsetof(struct IdentificationBasedDetectionDataType2__vehicleIdentification, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_vehicleIdentification_9 = {
	"vehicleIdentification",
	"vehicleIdentification",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_vehicleIdentification_tags_9,
	sizeof(asn_DEF_vehicleIdentification_tags_9)
		/sizeof(asn_DEF_vehicleIdentification_tags_9[0]) - 1, /* 1 */
	asn_DEF_vehicleIdentification_tags_9,	/* Same as above */
	sizeof(asn_DEF_vehicleIdentification_tags_9)
		/sizeof(asn_DEF_vehicleIdentification_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_vehicleIdentification_9,
	1,	/* Single element */
	&asn_SPC_vehicleIdentification_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_IdentificationBasedDetectionDataType2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IdentificationBasedDetectionDataType2, accumulativeDetection),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_accumulativeDetection_2,
		memb_accumulativeDetection_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accumulativeDetection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IdentificationBasedDetectionDataType2, passingVehicleTimeSeries),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_passingVehicleTimeSeries_4,
		memb_passingVehicleTimeSeries_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"passingVehicleTimeSeries"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IdentificationBasedDetectionDataType2, vehicleSpeed),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_vehicleSpeed_6,
		memb_vehicleSpeed_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IdentificationBasedDetectionDataType2, specificVehicleDetection),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_specificVehicleDetection_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"specificVehicleDetection"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IdentificationBasedDetectionDataType2, vehicleIdentification),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_vehicleIdentification_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleIdentification"
		},
	{ ATF_POINTER, 1, offsetof(struct IdentificationBasedDetectionDataType2, detectorStatus),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		memb_detectorStatus_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"detectorStatus"
		},
};
static const ber_tlv_tag_t asn_DEF_IdentificationBasedDetectionDataType2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IdentificationBasedDetectionDataType2_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* accumulativeDetection */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* passingVehicleTimeSeries */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* vehicleSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* specificVehicleDetection */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* vehicleIdentification */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* detectorStatus */
};
static asn_SEQUENCE_specifics_t asn_SPC_IdentificationBasedDetectionDataType2_specs_1 = {
	sizeof(struct IdentificationBasedDetectionDataType2),
	offsetof(struct IdentificationBasedDetectionDataType2, _asn_ctx),
	asn_MAP_IdentificationBasedDetectionDataType2_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IdentificationBasedDetectionDataType2 = {
	"IdentificationBasedDetectionDataType2",
	"IdentificationBasedDetectionDataType2",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IdentificationBasedDetectionDataType2_tags_1,
	sizeof(asn_DEF_IdentificationBasedDetectionDataType2_tags_1)
		/sizeof(asn_DEF_IdentificationBasedDetectionDataType2_tags_1[0]), /* 1 */
	asn_DEF_IdentificationBasedDetectionDataType2_tags_1,	/* Same as above */
	sizeof(asn_DEF_IdentificationBasedDetectionDataType2_tags_1)
		/sizeof(asn_DEF_IdentificationBasedDetectionDataType2_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IdentificationBasedDetectionDataType2_1,
	6,	/* Elements count */
	&asn_SPC_IdentificationBasedDetectionDataType2_specs_1	/* Additional specs */
};

