/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IdentificationBasedDetectionData_H_
#define	_IdentificationBasedDetectionData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <NativeReal.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IdentificationBasedDetectionData__deviceType {
	IdentificationBasedDetectionData__deviceType_infrared	= 1,
	IdentificationBasedDetectionData__deviceType_radioFrequency	= 2,
	IdentificationBasedDetectionData__deviceType_vehicleDetectionSystems	= 3,
	IdentificationBasedDetectionData__deviceType_magnetics	= 4,
	IdentificationBasedDetectionData__deviceType_barCodeScanner	= 5,
	IdentificationBasedDetectionData__deviceType_tagScanner	= 6,
	IdentificationBasedDetectionData__deviceType_other	= 7
	/*
	 * Enumeration is extensible
	 */
} e_IdentificationBasedDetectionData__deviceType;
typedef enum IdentificationBasedDetectionData__errorState {
	IdentificationBasedDetectionData__errorState_rSEFail	= 1,
	IdentificationBasedDetectionData__errorState_rSEConnectionFail	= 2,
	IdentificationBasedDetectionData__errorState_wirelessFail	= 3,
	IdentificationBasedDetectionData__errorState_unstableUtility	= 4,
	IdentificationBasedDetectionData__errorState_managementNeeded	= 5
} e_IdentificationBasedDetectionData__errorState;

/* IdentificationBasedDetectionData */
typedef struct IdentificationBasedDetectionData {
	long	 sequenceNumber;
	long	*deviceType	/* OPTIONAL */;
	OCTET_STRING_t	 vehicleId;
	long	*vehicleType	/* OPTIONAL */;
	long	*vehicleUse	/* OPTIONAL */;
	long	*detectionLane	/* OPTIONAL */;
	long	*detectionLaneMedian	/* OPTIONAL */;
	double	*detectionSpeed	/* OPTIONAL */;
	long	*occupancy	/* OPTIONAL */;
	long	*errorState	/* OPTIONAL */;
	OCTET_STRING_t	*tagInfo	/* OPTIONAL */;
	OCTET_STRING_t	*userData	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IdentificationBasedDetectionData_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_deviceType_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_errorState_19;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IdentificationBasedDetectionData;

#ifdef __cplusplus
}
#endif

#endif	/* _IdentificationBasedDetectionData_H_ */
#include <asn_internal.h>
