/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ImageProcessingBasedDetectionData_H_
#define	_ImageProcessingBasedDetectionData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeReal.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ImageProcessingBasedDetectionData__errorState {
	ImageProcessingBasedDetectionData__errorState_deviceFail	= 1,
	ImageProcessingBasedDetectionData__errorState_unstableUtility	= 2,
	ImageProcessingBasedDetectionData__errorState_connectionFail	= 3,
	ImageProcessingBasedDetectionData__errorState_imageProcessingFail	= 4,
	ImageProcessingBasedDetectionData__errorState_parameterInvalid	= 5,
	ImageProcessingBasedDetectionData__errorState_volumeError	= 6,
	ImageProcessingBasedDetectionData__errorState_managementNeeded	= 7
	/*
	 * Enumeration is extensible
	 */
} e_ImageProcessingBasedDetectionData__errorState;

/* Forward declarations */
struct OccupancyNonOccupancyHistory;

/* ImageProcessingBasedDetectionData */
typedef struct ImageProcessingBasedDetectionData {
	long	*dataDuration	/* OPTIONAL */;
	long	 volumeQuantity;
	long	*queueLength	/* OPTIONAL */;
	double	*occupancyRate	/* OPTIONAL */;
	double	*speedQuantity	/* OPTIONAL */;
	struct OccupancyNonOccupancyHistory	*occupancyNonOccupancyHistory	/* OPTIONAL */;
	long	*errorState	/* OPTIONAL */;
	OCTET_STRING_t	*userData	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ImageProcessingBasedDetectionData_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_errorState_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ImageProcessingBasedDetectionData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OccupancyNonOccupancyHistory.h"

#endif	/* _ImageProcessingBasedDetectionData_H_ */
#include <asn_internal.h>
