/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ImageProcessingBasedDetectionDataType2_H_
#define	_ImageProcessingBasedDetectionDataType2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <BIT_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ImageProcessingBasedDetectionDataType2__detectorStatus {
	ImageProcessingBasedDetectionDataType2__detectorStatus_processingFailure	= 0,
	ImageProcessingBasedDetectionDataType2__detectorStatus_operatingFailure	= 1
} e_ImageProcessingBasedDetectionDataType2__detectorStatus;

/* Forward declarations */
struct AccumulativeDetectionSeq;
struct PassingVehicleTimeSeriesSeq;
struct VehicleSpeedSeq;
struct DirectionalTrafficVolumeSeq;

/* ImageProcessingBasedDetectionDataType2 */
typedef struct ImageProcessingBasedDetectionDataType2 {
	struct ImageProcessingBasedDetectionDataType2__accumulativeDetection {
		A_SEQUENCE_OF(struct AccumulativeDetectionSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} accumulativeDetection;
	struct ImageProcessingBasedDetectionDataType2__passingVehicleTimeSeries {
		A_SEQUENCE_OF(struct PassingVehicleTimeSeriesSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} passingVehicleTimeSeries;
	struct ImageProcessingBasedDetectionDataType2__vehicleSpeed {
		A_SEQUENCE_OF(struct VehicleSpeedSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} vehicleSpeed;
	OCTET_STRING_t	 specificVehicleDetection;
	struct ImageProcessingBasedDetectionDataType2__congestionInfo {
		long	 congestionLength1;
		long	 vehicleStartPosition1;
		long	 congestionLength2;
		long	 vehicleStartPosition2;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} congestionInfo;
	struct ImageProcessingBasedDetectionDataType2__directionalTrafficVolume {
		A_SEQUENCE_OF(struct DirectionalTrafficVolumeSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} directionalTrafficVolume;
	BIT_STRING_t	*detectorStatus	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ImageProcessingBasedDetectionDataType2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ImageProcessingBasedDetectionDataType2;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AccumulativeDetectionSeq.h"
#include "PassingVehicleTimeSeriesSeq.h"
#include "VehicleSpeedSeq.h"
#include "DirectionalTrafficVolumeSeq.h"

#endif	/* _ImageProcessingBasedDetectionDataType2_H_ */
#include <asn_internal.h>
