/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ImageProcessingBasedDetectionData.h"

static int
errorState_8_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
errorState_8_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
errorState_8_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	errorState_8_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
errorState_8_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	errorState_8_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
errorState_8_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	errorState_8_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
errorState_8_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	errorState_8_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
errorState_8_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	errorState_8_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
errorState_8_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	errorState_8_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static const asn_INTEGER_enum_map_t asn_MAP_errorState_value2enum_8[] = {
	{ 1,	10,	"deviceFail" },
	{ 2,	15,	"unstableUtility" },
	{ 3,	14,	"connectionFail" },
	{ 4,	19,	"imageProcessingFail" },
	{ 5,	16,	"parameterInvalid" },
	{ 6,	11,	"volumeError" },
	{ 7,	16,	"managementNeeded" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_errorState_enum2value_8[] = {
	2,	/* connectionFail(3) */
	0,	/* deviceFail(1) */
	3,	/* imageProcessingFail(4) */
	6,	/* managementNeeded(7) */
	4,	/* parameterInvalid(5) */
	1,	/* unstableUtility(2) */
	5	/* volumeError(6) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_errorState_specs_8 = {
	asn_MAP_errorState_value2enum_8,	/* "tag" => N; sorted by tag */
	asn_MAP_errorState_enum2value_8,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	8,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_errorState_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_errorState_8 = {
	"errorState",
	"errorState",
	errorState_8_free,
	errorState_8_print,
	errorState_8_constraint,
	errorState_8_decode_ber,
	errorState_8_encode_der,
	errorState_8_decode_xer,
	errorState_8_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_errorState_tags_8,
	sizeof(asn_DEF_errorState_tags_8)
		/sizeof(asn_DEF_errorState_tags_8[0]) - 1, /* 1 */
	asn_DEF_errorState_tags_8,	/* Same as above */
	sizeof(asn_DEF_errorState_tags_8)
		/sizeof(asn_DEF_errorState_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_errorState_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ImageProcessingBasedDetectionData_1[] = {
	{ ATF_POINTER, 1, offsetof(struct ImageProcessingBasedDetectionData, dataDuration),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataDuration"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ImageProcessingBasedDetectionData, volumeQuantity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"volumeQuantity"
		},
	{ ATF_POINTER, 6, offsetof(struct ImageProcessingBasedDetectionData, queueLength),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"queueLength"
		},
	{ ATF_POINTER, 5, offsetof(struct ImageProcessingBasedDetectionData, occupancyRate),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancyRate"
		},
	{ ATF_POINTER, 4, offsetof(struct ImageProcessingBasedDetectionData, speedQuantity),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"speedQuantity"
		},
	{ ATF_POINTER, 3, offsetof(struct ImageProcessingBasedDetectionData, occupancyNonOccupancyHistory),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OccupancyNonOccupancyHistory,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancyNonOccupancyHistory"
		},
	{ ATF_POINTER, 2, offsetof(struct ImageProcessingBasedDetectionData, errorState),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_errorState_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"errorState"
		},
	{ ATF_POINTER, 1, offsetof(struct ImageProcessingBasedDetectionData, userData),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userData"
		},
};
static const ber_tlv_tag_t asn_DEF_ImageProcessingBasedDetectionData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ImageProcessingBasedDetectionData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dataDuration */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* volumeQuantity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* queueLength */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* occupancyRate */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* speedQuantity */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* occupancyNonOccupancyHistory */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* errorState */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* userData */
};
static asn_SEQUENCE_specifics_t asn_SPC_ImageProcessingBasedDetectionData_specs_1 = {
	sizeof(struct ImageProcessingBasedDetectionData),
	offsetof(struct ImageProcessingBasedDetectionData, _asn_ctx),
	asn_MAP_ImageProcessingBasedDetectionData_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ImageProcessingBasedDetectionData = {
	"ImageProcessingBasedDetectionData",
	"ImageProcessingBasedDetectionData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ImageProcessingBasedDetectionData_tags_1,
	sizeof(asn_DEF_ImageProcessingBasedDetectionData_tags_1)
		/sizeof(asn_DEF_ImageProcessingBasedDetectionData_tags_1[0]), /* 1 */
	asn_DEF_ImageProcessingBasedDetectionData_tags_1,	/* Same as above */
	sizeof(asn_DEF_ImageProcessingBasedDetectionData_tags_1)
		/sizeof(asn_DEF_ImageProcessingBasedDetectionData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ImageProcessingBasedDetectionData_1,
	8,	/* Elements count */
	&asn_SPC_ImageProcessingBasedDetectionData_specs_1	/* Additional specs */
};

