/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IpmstscdData_H_
#define	_IpmstscdData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DetectorControllerInfo;
struct DetectorInfoSeq;

/* IpmstscdData */
typedef struct IpmstscdData {
	struct DetectorControllerInfo	*detectorControllerInfo	/* OPTIONAL */;
	struct IpmstscdData__detectorInfo {
		A_SEQUENCE_OF(struct DetectorInfoSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *detectorInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpmstscdData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IpmstscdData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DetectorControllerInfo.h"
#include "DetectorInfoSeq.h"

#endif	/* _IpmstscdData_H_ */
#include <asn_internal.h>
