/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_OccupancyBasedDetectionDataType2_H_
#define	_OccupancyBasedDetectionDataType2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <BIT_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OccupancyBasedDetectionDataType2__detectorStatus {
	OccupancyBasedDetectionDataType2__detectorStatus_processingFailure	= 0,
	OccupancyBasedDetectionDataType2__detectorStatus_operatingFailure	= 1
} e_OccupancyBasedDetectionDataType2__detectorStatus;

/* Forward declarations */
struct AccumulativeDetectionSeq;
struct PassingVehicleTimeSeriesSeq;
struct VehicleSpeedSeq;

/* OccupancyBasedDetectionDataType2 */
typedef struct OccupancyBasedDetectionDataType2 {
	struct OccupancyBasedDetectionDataType2__accumulativeDetection {
		A_SEQUENCE_OF(struct AccumulativeDetectionSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} accumulativeDetection;
	struct OccupancyBasedDetectionDataType2__passingVehicleTimeSeries {
		A_SEQUENCE_OF(struct PassingVehicleTimeSeriesSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} passingVehicleTimeSeries;
	struct OccupancyBasedDetectionDataType2__vehicleSpeed {
		A_SEQUENCE_OF(struct VehicleSpeedSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} vehicleSpeed;
	OCTET_STRING_t	 specificVehicleDetection;
	BIT_STRING_t	*detectorStatus	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OccupancyBasedDetectionDataType2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OccupancyBasedDetectionDataType2;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AccumulativeDetectionSeq.h"
#include "PassingVehicleTimeSeriesSeq.h"
#include "VehicleSpeedSeq.h"

#endif	/* _OccupancyBasedDetectionDataType2_H_ */
#include <asn_internal.h>
