/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_OccupancyBasedDetectionData_H_
#define	_OccupancyBasedDetectionData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <NativeReal.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OccupancyBasedDetectionData__errorState {
	OccupancyBasedDetectionData__errorState_openCircuit	= 1,
	OccupancyBasedDetectionData__errorState_shortCircuit	= 2,
	OccupancyBasedDetectionData__errorState_occupancyError	= 3,
	OccupancyBasedDetectionData__errorState_nonOccupancyError	= 4,
	OccupancyBasedDetectionData__errorState_volumeError	= 5,
	OccupancyBasedDetectionData__errorState_parameterInvalid	= 6,
	OccupancyBasedDetectionData__errorState_managementNeeded	= 7
} e_OccupancyBasedDetectionData__errorState;

/* Forward declarations */
struct OccupancyNonOccupancyHistory;

/* OccupancyBasedDetectionData */
typedef struct OccupancyBasedDetectionData {
	long	*occupancyDataDuration	/* OPTIONAL */;
	BOOLEAN_t	 occupancyState;
	long	 occupancyStateDuration;
	long	 occupancyPreviousStateDuration;
	double	 occupancyRate;
	double	*speed	/* OPTIONAL */;
	long	 volume;
	struct OccupancyBasedDetectionData__occupancyNonOccupancyHistory {
		A_SEQUENCE_OF(struct OccupancyNonOccupancyHistory) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *occupancyNonOccupancyHistory;
	long	*errorState	/* OPTIONAL */;
	OCTET_STRING_t	*userData	/* OPTIONAL */;
	long	*targetType	/* OPTIONAL */;
	BOOLEAN_t	*directionDiscrimination	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OccupancyBasedDetectionData_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_errorState_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_OccupancyBasedDetectionData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OccupancyNonOccupancyHistory.h"

#endif	/* _OccupancyBasedDetectionData_H_ */
#include <asn_internal.h>
