/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PassingVehicleTimeSeriesSeq_H_
#define	_PassingVehicleTimeSeriesSeq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PassingVehicleTimeSeriesSeq__detectionStatus {
	PassingVehicleTimeSeriesSeq__detectionStatus_normal	= 0,
	PassingVehicleTimeSeriesSeq__detectionStatus_failure	= 1,
	PassingVehicleTimeSeriesSeq__detectionStatus_dataInvalid	= 2
} e_PassingVehicleTimeSeriesSeq__detectionStatus;

/* PassingVehicleTimeSeriesSeq */
typedef struct PassingVehicleTimeSeriesSeq {
	long	 detectorNumber;
	long	*detectionStatus	/* OPTIONAL */;
	OCTET_STRING_t	 vehiclePassageHistory;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PassingVehicleTimeSeriesSeq_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_detectionStatus_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PassingVehicleTimeSeriesSeq;

#ifdef __cplusplus
}
#endif

#endif	/* _PassingVehicleTimeSeriesSeq_H_ */
#include <asn_internal.h>
