/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Time_H_
#define	_Time_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Time__secondFractions_PR {
	Time__secondFractions_PR_NOTHING,	/* No components present */
	Time__secondFractions_PR_deciSeconds,
	Time__secondFractions_PR_centiSeconds,
	Time__secondFractions_PR_milliseconds,
	/* Extensions may appear below */
	
} Time__secondFractions_PR;

/* Time */
typedef struct Time {
	long	*year	/* OPTIONAL */;
	long	*month	/* OPTIONAL */;
	long	*day	/* OPTIONAL */;
	long	 hour	/* DEFAULT 0 */;
	long	 minute	/* DEFAULT 0 */;
	long	 second	/* DEFAULT 0 */;
	struct Time__secondFractions {
		Time__secondFractions_PR present;
		union Time__secondFractions_u {
			long	 deciSeconds;
			long	 centiSeconds;
			long	 milliseconds;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} secondFractions;
	struct Time__timeZone {
		long	 hour	/* DEFAULT 0 */;
		long	 minute	/* DEFAULT 0 */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *timeZone;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Time_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Time;

#ifdef __cplusplus
}
#endif

#endif	/* _Time_H_ */
#include <asn_internal.h>
