/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VehicleIdentificationSeq_H_
#define	_VehicleIdentificationSeq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleIdentificationSeq */
typedef struct VehicleIdentificationSeq {
	OCTET_STRING_t	 vehicleID;
	OCTET_STRING_t	*data	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleIdentificationSeq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleIdentificationSeq;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleIdentificationSeq_H_ */
#include <asn_internal.h>
