/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO-10711-IpmstscdData"
 * 	found in "../Annex_A_10711_v3.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VehicleSpeedSeq_H_
#define	_VehicleSpeedSeq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleSpeedSeq__vehicleType {
	VehicleSpeedSeq__vehicleType_fourBus	= 1,
	VehicleSpeedSeq__vehicleType_fourLargeSizeTruck	= 2,
	VehicleSpeedSeq__vehicleType_fourSmallSizeTruck	= 4,
	VehicleSpeedSeq__vehicleType_fourElse	= 8,
	VehicleSpeedSeq__vehicleType_twoLargeSizeVehicle	= 16,
	VehicleSpeedSeq__vehicleType_twoElse	= 32
} e_VehicleSpeedSeq__vehicleType;

/* VehicleSpeedSeq */
typedef struct VehicleSpeedSeq {
	long	 detectorNumber;
	long	 vehicleType;
	long	 velocity;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSpeedSeq_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_vehicleType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSpeedSeq;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSpeedSeq_H_ */
#include <asn_internal.h>
